# Generated by Django 6.1.1 on 2026-09-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthdays', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthday',
            name='last_greeting_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='birthday',
            name='full_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='birthday',
            name='relation',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
