# Generated by Django 6.1.1 on 2026-09-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthdays', '0002_birthday_last_greeting_year_alter_birthday_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthday',
            name='last_reminder_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
