# Generated by Django 6.1.1 on 2026-09-28 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familyuser',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='familyuser',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='familyuser',
            name='role',
            field=models.CharField(choices=[('USER', 'Oddiy foydalanuvchi'), ('ADMIN', 'Admin'), ('SUPER_ADMIN', 'Super admin')], default='USER', max_length=20),
        ),
        migrations.AlterField(
            model_name='familyuser',
            name='full_name',
            field=models.CharField(max_length=150),
        ),
    ]
